spring.application.name=EduTech

spring.datasource.url=jdbc:postgresql://localhost:5432/edutech_db
spring.datasource.username=edutech_admin
spring.datasource.password=edutech_password
spring.datasource.driver-class-name=org.postgresql.Driver
